python3 train.py --img 640 --batch 8 --epochs 20 --data dataset.yaml --weights yolov5l.pt
python3 train.py --img 640 --batch 8 --epochs 30 --data dataset.yaml --weights yolov5l.pt
python3 train.py --img 640 --batch 8 --epochs 50 --data dataset2.yaml --weights yolov5l.pt
python3 train.py --img 640 --batch 8 --epochs 50 --data dataset.yaml --weights yolov5l.pt
python3 train.py --img 480 --batch 8 --epochs 20 --data dataset.yaml --weights yolov5l.pt
python3 train.py --img 480 --batch 8 --epochs 30 --data dataset.yaml --weights yolov5l.pt
python3 train.py --img 480 --batch 8 --epochs 50 --data dataset.yaml --weights yolov5l.pt
python3 train.py --img 480 --batch 8 --epochs 50 --data dataset2.yaml --weights yolov5l.pt
python3 train.py --img 320 --batch 8 --epochs 20 --data dataset.yaml --weights yolov5l.pt
python3 train.py --img 320 --batch 8 --epochs 30 --data dataset.yaml --weights yolov5l.pt
python3 train.py --img 320 --batch 8 --epochs 50 --data dataset.yaml --weights yolov5l.pt
python3 train.py --img 320 --batch 8 --epochs 50 --data dataset2.yaml --weights yolov5l.pt
python3 train.py --img 640 --batch 8 --epochs 20 --data dataset.yaml --weights ''
python3 train.py --img 640 --batch 8 --epochs 30 --data dataset.yaml --weights ''
python3 train.py --img 640 --batch 8 --epochs 50 --data dataset2.yaml --weights ''
python3 train.py --img 640 --batch 8 --epochs 50 --data dataset.yaml --weights ''
python3 train.py --img 480 --batch 8 --epochs 20 --data dataset.yaml --weights ''
python3 train.py --img 480 --batch 8 --epochs 30 --data dataset.yaml --weights ''
python3 train.py --img 480 --batch 8 --epochs 50 --data dataset.yaml --weights ''
python3 train.py --img 480 --batch 8 --epochs 50 --data dataset2.yaml --weights ''
python3 train.py --img 320 --batch 8 --epochs 20 --data dataset.yaml --weights ''
python3 train.py --img 320 --batch 8 --epochs 30 --data dataset.yaml --weights ''
python3 train.py --img 320 --batch 8 --epochs 50 --data dataset.yaml --weights ''
python3 train.py --img 320 --batch 8 --epochs 50 --data dataset2.yaml --weights ''
